# Multi-order Healpix

In [1]:
# imports
import numpy as np

import healpy 

from astropy import units
from astropy.coordinates import SkyCoord
from astropy.coordinates import Angle

import astropy_healpix

from mocpy import MOC

# Set nside

In [2]:
nside = astropy_healpix.pixel_resolution_to_nside(0.1*units.arcsec)
nside

2097152

In [3]:
max_order = int(np.log2(nside))
max_order

21

## This seems one number to low..

# Find pixel indices inside the localization

    https://zonca.dev/2020/10/example-healpy-query_disc.html

## FRB localization centroid (fake)

In [4]:
frb_cen = SkyCoord(ra=326.1052292, dec=-40.9000278, unit='deg')

In [5]:
frb_cen.galactic.b

<Latitude -49.41466408 deg>

In [15]:
Angle(frb_cen.galactic.l), Angle(frb_cen.galactic.b)

(<Angle 0.74244708 deg>, <Angle -49.41466408 deg>)

In [16]:
moc = MOC.from_elliptical_cone(lon=Angle(frb_cen.galactic.l), 
                               lat=Angle(frb_cen.galactic.b),
                    a=Angle(0.4, units.arcsec), b=Angle(0.3, units.arcsec), 
                               pa=Angle(45, units.deg),
                               max_depth=max_order+1) # Note the +1

In [17]:
uniq = moc._interval_set._intervals
uniq

array([[2488431636922712064, 2488431636922761216],
       [2488431636924121088, 2488431636924203008],
       [2488431636924219392, 2488431636924334080],
       [2488431636924547072, 2488431636924563456],
       [2488431636924579840, 2488431636924858368],
       [2488431636925104128, 2488431636925120512],
       [2488431636925284352, 2488431636925317120],
       [2488431636925399040, 2488431636925726720],
       [2488431636925743104, 2488431636925906944],
       [2488431636926955520, 2488431636927954944],
       [2488431636927971328, 2488431636927987712],
       [2488431637014069248, 2488431637014085632],
       [2488431637014102016, 2488431637014118400],
       [2488431637014200320, 2488431637014216704],
       [2488431637014249472, 2488431637014511616],
       [2488431637014773760, 2488431637014806528],
       [2488431637014822912, 2488431637014904832],
       [2488431637017133056, 2488431637017460736],
       [2488431637017526272, 2488431637017542656],
       [2488431637017657344, 24

In [18]:
type(uniq)

numpy.ndarray

In [10]:
moc.spatial_resolution_to_order(Angle(0.1, units.arcsec))

22

# Grab RA, DEC

In [19]:
level, ipix = astropy_healpix.uniq_to_level_ipix(uniq)
level, ipix

(array([[29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29],
        [29, 29]]),
 array([[1335510132315865088, 1335510132315914240],
        [1335510132317274112, 1335510132317356032],
        [1335510132317372416, 1335510132317487104],
        [1335510132317700096, 1335510132317716480],
        [1335510132317732864, 1335510132318011392],
        [1335510132318257152, 1335510132318273536],
        [1335510132318437376, 1335510132318470144],
        [1335510132318552064, 1335510132318879744],
        [1335510132318896128, 1335510132319059968],
        [1335510132320108544, 1335510132321107968],
        [1335510132321124352, 1335510132321140736],
        [1335510132407222272, 1335510132407238656],
        [13355

## New nside

In [20]:
new_nside = astropy_healpix.level_to_nside(level)
new_nside

array([[536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912],
       [536870912, 536870912]])

## lon, lat

In [21]:
lon, lat = astropy_healpix.healpix_to_lonlat(ipix, new_nside, order='nested')
lon.to('deg'), lat.to('deg')

(<Longitude [[322.4023068 , 322.4021244 ],
             [322.40225315, 322.40223169],
             [322.40224242, 322.40216732],
             [322.40217805, 322.40215659],
             [322.40216732, 322.4023819 ],
             [322.4023819 , 322.40242481],
             [322.40239263, 322.40242481],
             [322.40234971, 322.40241408],
             [322.40239263, 322.40246773],
             [322.40229607, 322.4023068 ],
             [322.40228534, 322.40229607],
             [322.40215659, 322.40213513],
             [322.40214586, 322.40210295],
             [322.40213513, 322.40211368],
             [322.40216732, 322.40208149],
             [322.4021244 , 322.40211368],
             [322.4021244 , 322.40210295],
             [322.40221024, 322.40227461],
             [322.40223169, 322.40224242],
             [322.40216732, 322.40219951]] deg>,
 <Latitude [[-5.75763556, -5.75775455],
            [-5.75762641, -5.75762641],
            [-5.75761725, -5.75764471],
            [-